### ISSUE TITLE
Border radius is off in navbar's input when focused

### ISSUE THREAD

**Issue by pwoosam** [pwoosam/hedera-nft-explorer#6]
Looking at the navbar's input, when clicking inside, the blue border's radius does not match the radius of the input.
![image](https://github.com/pwoosam/hedera-nft-explorer/assets/18713517/88541c89-e57d-416a-8cb0-39deb1a45a44)

The serial number input looks fine when focused
![image](https://github.com/pwoosam/hedera-nft-explorer/assets/18713517/592ad5a9-7b4c-404d-95c4-235d092b79d7)

**Comment by aconstas** [comment]
Pull request sent! :) I removed the BorderRadius property from the sx prop in the Navbar component

**Comment by pwoosam** [comment]
Fixed by #7
